// Code generated by Slice Machine. DO NOT EDIT.

import Article from './Article/index.svelte';
import CallToAction from './CallToAction/index.svelte';
import Hero from './Hero/index.svelte';

export const components = {
	article: Article,
	call_to_action: CallToAction,
	hero: Hero
};
